import Testing
import Foundation
@testable import AIDream

@MainActor // 确保测试在主线程运行，同步访问 FavoriteService
struct AIDreamTests {
    @Test func videoDataInitialization() async throws {
        let video = VideoData(
            id: 1,
            title: "Vision AI Test",
            introduction: "A cinematic masterpiece generated by AI",
            videoURL: URL(string: "https://example.com/video.mp4"),
            coverURL: URL(string: "https://example.com/cover.jpg"),
            userName: "Creator_One",
            userAvatarURL: nil,
            starCount: 120,
            width: 1080,
            height: 1920
        )

        #expect(video.id == 1)
        #expect(video.title == "Vision AI Test")
        #expect(video.userName == "Creator_One")
        #expect(video.aspectRatio == 1920.0 / 1080.0)
    }

    @Test func favoriteServiceSyncLogic() async throws {
        let service = FavoriteService.shared
        let video = VideoData(
            id: 999,
            title: "Test Favorite",
            introduction: "",
            videoURL: nil,
            coverURL: nil,
            userName: "Tester",
            userAvatarURL: nil,
            starCount: 0,
            width: 100,
            height: 100
        )

        // 确保初始状态清理
        if service.isFavorited(999) {
            service.toggleFavorite(video)
        }

        #expect(service.isFavorited(999) == false)

        // 测试收藏逻辑（由于标记了 @MainActor，这里是同步生效的）
        service.toggleFavorite(video)
        #expect(service.isFavorited(999) == true)
        #expect(service.favoriteVideos.contains(where: { $0.id == 999 }))

        // 测试取消收藏逻辑
        service.toggleFavorite(video)
        #expect(service.isFavorited(999) == false)
    }
}
