import Testing
import Foundation
@testable import AIDream

struct AIDreamTests {
    @Test func videoDataInitialization() async throws {
        // 使用当前 VideoData 结构体定义进行初始化
        let video = VideoData(
            id: 1,
            title: "Vision AI Test",
            introduction: "A cinematic masterpiece generated by AI",
            videoURL: URL(string: "https://example.com/video.mp4"),
            coverURL: URL(string: "https://example.com/cover.jpg"),
            userName: "Vision_Creator",
            userAvatarURL: nil,
            starCount: 120,
            width: 1080,
            height: 1920
        )

        #expect(video.id == 1)
        #expect(video.title == "Vision AI Test")
        #expect(video.userName == "Vision_Creator")
        #expect(video.aspectRatio == 1920.0 / 1080.0)
    }

    @Test func favoriteServiceLogic() async throws {
        let service = FavoriteService.shared
        let video = VideoData(
            id: 888,
            title: "Test Favorite",
            introduction: "",
            videoURL: nil,
            coverURL: nil,
            userName: "Tester",
            userAvatarURL: nil,
            starCount: 0,
            width: 100,
            height: 100
        )

        // 确保初始状态
        if service.isFavorited(888) {
            service.toggleFavorite(video)
        }

        // 测试收藏逻辑
        service.toggleFavorite(video)
        #expect(service.isFavorited(888) == true)

        // 测试取消收藏
        service.toggleFavorite(video)
        #expect(service.isFavorited(888) == false)
    }
}
